services:
  kafka-1:
    image: apache/kafka:4.1.1
    container_name: kafka-1
    hostname: kafka-1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      
      # listeners
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:29092,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,INTERNAL://kafka-1:29092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Настройки репликации и надежности
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      
      # Настройки хранения
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_NUM_PARTITIONS: 8
      
      # Надежность контроллера
      KAFKA_CONTROLLER_QUORUM_ELECTION_TIMEOUT_MS: 5000
      KAFKA_CONTROLLER_QUORUM_FETCH_TIMEOUT_MS: 5000
      KAFKA_CONTROLLER_QUORUM_REQUEST_TIMEOUT_MS: 8000
      
      KAFKA_AUTHORIZER_CLASS_NAME: ""
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      
    ports:
      - "19092:9094" 
    volumes:
      - kafka-data-1:/var/lib/kafka/data
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka-1:9092 > /dev/null 2>&1"]
      interval: 15s
      timeout: 15s
      retries: 20
      start_period: 90s

  kafka-2:
    image: apache/kafka:4.1.1
    container_name: kafka-2
    hostname: kafka-2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      
      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:29092,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,INTERNAL://kafka-2:29092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Настройки репликации и надежности
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      
      # Настройки хранения
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_NUM_PARTITIONS: 8
      
      # Надежность контроллера
      KAFKA_CONTROLLER_QUORUM_ELECTION_TIMEOUT_MS: 5000
      KAFKA_CONTROLLER_QUORUM_FETCH_TIMEOUT_MS: 5000
      KAFKA_CONTROLLER_QUORUM_REQUEST_TIMEOUT_MS: 8000
      
      KAFKA_AUTHORIZER_CLASS_NAME: ""
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      
    ports:
      - "29092:9094" 
    volumes:
      - kafka-data-2:/var/lib/kafka/data
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka-2:9092 > /dev/null 2>&1"]
      interval: 15s
      timeout: 15s
      retries: 20
      start_period: 90s

  kafka-3:
    image: apache/kafka:4.1.1
    container_name: kafka-3
    hostname: kafka-3
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      
      # Listeners 
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:29092,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,INTERNAL://kafka-3:29092,EXTERNAL://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # Настройки репликации и надежности
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      
      # Настройки хранения
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_NUM_PARTITIONS: 8
      
      # Надежность контроллера
      KAFKA_CONTROLLER_QUORUM_ELECTION_TIMEOUT_MS: 5000
      KAFKA_CONTROLLER_QUORUM_FETCH_TIMEOUT_MS: 5000
      KAFKA_CONTROLLER_QUORUM_REQUEST_TIMEOUT_MS: 8000
      
      KAFKA_AUTHORIZER_CLASS_NAME: ""
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      
    ports:
      - "39092:9094" 
    volumes:
      - kafka-data-3:/var/lib/kafka/data
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka-3:9092 > /dev/null 2>&1"]
      interval: 15s
      timeout: 15s
      retries: 20
      start_period: 90s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: test-kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
      KAFKA_CLUSTERS_0_READONLY: "false"
    networks:
      - kafka-net
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy  
      kafka-3:
        condition: service_healthy

volumes:
  kafka-data-1:
  kafka-data-2:
  kafka-data-3:

networks:
  kafka-net:
    driver: bridge